def tf_path = "codeonline/terraform/vm_img"

pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        ENV_INVENTORY = "${env.WORKSPACE}/${run_id}/codeonline/inventory"
    }

    parameters {
        string(name: 'run_id', defaultValue: "${currentBuild.startTimeInMillis}", description: 'Auto Generated Unique Value to Tag Resources - Do Not Change')
    }

    stages {
        stage('Checkout Main Branch') {
            steps {
                dir("${run_id}/codeonline"){
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[url: 'https://github.com/avishka2k/codeonline-infra.git', credentialsId: "github-token"]]
                    ])
                }   
            }
        }

        stage('Checkout Config File') {
            steps {
                script {
                    def props = readProperties file: "${env.WORKSPACE}/${run_id}/codeonline/configs.properties"
                    for (p in props) {
                        env."${p.key}" = "${p.value}"
                    }
                    
                    sh script: """
                        echo "$props.name}"
                    """
                }        
            }
        }

        stage('Create GCP VM') {
            steps {
                script {
                    sh script: """
                        cd "${run_id}/${tf_path}"
                        terraform init
                        terraform plan
                        terraform apply --auto-approve"
                    """
                }
            }
        }

        post { 
            always { 
                script {
                    input('continue')
                    
                }           
                deleteDir()
            }
        }
    }
}