def tf_path = "codeonline/terraform/create_image"

pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        ENV_INVENTORY = "${env.WORKSPACE}/${run_id}/codeonline/inventory"
    }

    parameters {
        string(name: 'run_id', defaultValue: "${currentBuild.startTimeInMillis}", description: 'Auto Generated Unique Value to Tag Resources - Do Not Change')
    }

    stages {
        stage('Checkout Main Branch') {
            steps {
                dir("${run_id}/codeonline"){
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[url: 'https://github.com/avishka2k/codeonline-infra.git', credentialsId: "github-token"]]
                    ])
                }   
            }
        }

        stage('Checkout Config File') {
            steps {
                script {
                    def props = readProperties file: "${env.WORKSPACE}/${run_id}/codeonline/configs.properties"
                    for (p in props) {
                        env."${p.key}" = "${p.value}"
                    }
                    
                    sh script: """
                      echo "$props.name}"
                    """
                }        
            }
        }

        stage('Create GCP VM') {
            steps {
                script {
                    sh script: """
                        cd "${run_id}/${tf_path}"
                        terraform init
                        terraform apply --auto-approve -var="inventory=${env.ENV_INVENTORY}"
                    """
                }
            }
        }

        stage('Configure machine') {
            steps {
                script {
                    // sh script: """
                    //     cd "${run_id}/codeonline/ansible"
                    //     ansible-playbook vm-config.yml -i ${env.ENV_INVENTORY}
                    // """
                    sh script: "echo 'hi'"
            }
        }

        stage('Sleep') {
            steps {
                script {
                    input('continue')
                }
            }
        }
    }

    post { 
        always { 
            script {
                sh script: """
                    cd "${run_id}/${tf_path}"
                    terraform destroy --auto-approve -var="inventory=${env.ENV_INVENTORY}"
                """
            }           
            deleteDir()
        }
    }
}