pipeline {
    agent any
    
    stages {
        stage('Checkout Branch') {
            steps {
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/avishka2k/codeonline-infra.git', credentialsId: "github-token"]]
                ])
            }
        }
    }

    post { 
        always { 
            deleteDir()
        }
    }
}