pipeline {
    agent any

    stages {
        stage('Checkout Main Branch') {
            steps {
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/avishka2k/codeonline-infra.git', credentialsId: "github-token"]]
                ])
            }
        }

        stage('Checkout Config File') {
            steps {
                def props = readProperties file: './config.properties'
                
                sh script: "${props}"
                sh script: "one ${props.name}"
            }
        }
    }

    post { 
        always { 
            deleteDir()
        }
    }
}