---

- name: Install packages based on package.json using the npm
  npm:
    path: "{{workspace}}/{{runid}}/dev/{{root_dir}}/"
    state: present

- name: npm build
  command: CI= npm run build
  args:
    chdir: "{{workspace}}/{{runid}}/dev/{{root_dir}}/"

- name: Remove files and directories
  find:
    paths: "{{workspace}}/{{runid}}/dev"
    patterns: '*'
    recurse: yes
  register: files_to_remove

- name: Exclude 'build' directory
  set_fact:
    files_to_keep: "{{ files_to_remove.files | rejectattr('path', 'match', '^{{workspace}}/{{runid}}/dev/build/') | map(attribute='path') | list }}"

- name: Remove files and directories (except 'build')
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_keep }}"
