---
- name: npm install
  command: npm install
  args:
    chdir: "{{workdir}}"

- name: npm build
  shell: CI=false npm run build
  args:
    chdir: "{{workdir}}"

- name: Clean dir (excluding 'build/')
  shell: |
    find . -mindepth 1 -maxdepth 1 -type d ! -name 'build' -exec rm -r {} \;
    find . -mindepth 1 -maxdepth 1 ! -name 'build' -exec rm -f {} \;
  args:
    chdir: "{{workdir}}"

- name: Copy app.yaml
  copy:
    src: app.yaml
    dest: "{{workdir}}"
    mode: 0755
  
- name: App deploy
  command: gcloud app deploy -q --version="{{version}}"
  args:
    chdir: "{{workdir}}"

- name: Output
  command: gcloud app browse -s codeonline-18
  register: browse_app

- name: msg
  debug:
    msg: "{{browse_app.stdout}}"