---
- name: Create GCP Compute Engine Image
  tasks:
    - name: Set GCP authentication
      community.general.gcp_auth:
        credentials_file: "../../../terraform/modules/codeonline-gcp.json"

    # - name: Create image from instance
    #   gcp_compute_image:
    #     name: "new-image-name"
    #     source_instance: "projects/your-project-id/zones/your-zone/instances/instance-group-instance-name"

    # - name: Cleanup (optional)
    #   gcp_compute_instance_group_manager:
    #     name: "instance-group-manager-name"
    #     state: "absent"
