---
- name: Apt update and upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt pkg
  become: true
  apt:
    pkg:
    - openjdk-11-jdk
    - nodejs

- name: Download code-server latest
  get_url:
    url: https://github.com/coder/code-server/releases/download/v4.2.0/code-server-4.2.0-linux-amd64.tar.gz
    dest: /home/{{ username }}/
    mode: '0755'

- name: Extract code-server into /home/{{ username }}
  unarchive:
    src: /home/{{ username }}/code-server-4.2.0-linux-amd64.tar.gz
    dest: /home/{{ username }}/