---
- name: Copy startup script
  become: true
  copy:
    src: "startup.sh"
    dest: "/home/avishkaprabathg"
    mode: "0755"
    
# - name: Run script
#   shell: "/home/avishkaprabathg/startup.sh"
#   register: shell_out

# - name: Shell log
#   debug:
#     var: shell_out