sudo code-server --install-extension esbenp.prettier-vscode
sudo code-server --install-extension redhat.vscode-yaml
sudo code-server --install-extension ms-python.python
sudo code-server --install-extension redhat.java
sudo code-server --install-extension Betajob.modulestf
sudo code-server --install-extension redhat.vscode-xml
sudo code-server --install-extension hediet.vscode-drawio-insiders-build
sudo code-server --install-extension richardwillis.vscode-gradle
sudo code-server --install-extension vscjava.vscode-java-pack
sudo code-server --install-extension vscjava.vscode-maven
sudo code-server --install-extension pivotal.vscode-spring-boot
sudo code-server --install-extension pivotal.vscode-boot-dev-pack
sudo code-server --install-extension vscjava.vscode-spring-initializr
sudo code-server --install-extension vscjava.vscode-spring-boot-dashboard